export default {
  dataSource: 'DataSource',
  keyValueSource: 'KeyValueSource',
  keyValueSourcePart: 'KeyValueSourcePart',
  localStorageFn: 'localStorage',
  localStorage: 'LocalStorage',
  localStoragePartFn: 'localStoragePart',
  localStoragePart: 'LocalStoragePart',
  sessionStorageFn: 'sessionStorage',
  sessionStorage: 'SessionStorage',
  sessionStoragePartFn: 'sessionStoragePart',
  sessionStoragePart: 'SessionStoragePart',
  memoryStorageFn: 'memoryStorage',
  memoryStorage: 'MemoryStorage',
  memoryStoragePartFn: 'memoryStoragePart',
  memoryStoragePart: 'MemoryStoragePart',
  cookieFn: 'cookie',
  cookie: 'Cookie',
  cookiePartFn: 'cookiePart',
  cookiePart: 'CookiePart',
  cookieParams: 'CookieParams',
  cookieData: 'CookieData',
};
