export default {
  $: '$',
  initialize: 'initialize',
  complete: 'complete',
  manage: 'manage',
  get: 'get',
  set: 'set',
  update: 'update',
  reset: 'reset',
  compareBy: 'compareBy',
  connect: 'connect',
  useLazyEmission: 'useLazyEmission',
  useLazyEmissionOnce: 'useLazyEmissionOnce',
  select: 'select',
  zip: 'zip',
  wait: 'wait',
  receive: 'receive',
  transmit: 'transmit',
  effect: 'effect',
  tap: 'tap',
};
